name: Go
permissions:
  contents: read

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Test Coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

    - name: Report Code Coverage
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: false 
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

    - name: GolangCI-Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        skip-cache: true

  static-analysis:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Nil panic checks
        uses: qbaware/nilaway-action@v0
        with:
          package-to-scan: ./...